[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings=["@openzeppelin/contracts=node_modules/@openzeppelin/contracts"]

[rpc_endpoints]
anvil_local="${ANVIL_LOCAL_TESTNET}"
mumbai = "${MUMBAI_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC}"
optimism_sepolia = "${OPTIMISM_SEPOLIA}"
eth_sepolia = "${ETHEREUM_SEPOLIA}"


eth_mainnet = "${ETHEREUM_MAINNET}"
base_mainnet = "${BASE_MAINNET}"
polygon_mainnet = "${POLYGON_MAINNET}"
optimism_mainnet = "${OPTIMISM_MAINNET}"




# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
